/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.smaC.Company;
import org.xtext.smaC.Mapping;
import org.xtext.smaC.PersonalizedStruct;
import org.xtext.smaC.Properties;
import org.xtext.smaC.SmaCPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Company</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.impl.CompanyImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.smaC.impl.CompanyImpl#getNameAttributeAddress <em>Name Attribute Address</em>}</li>
 *   <li>{@link org.xtext.smaC.impl.CompanyImpl#getNameAttributeCompany <em>Name Attribute Company</em>}</li>
 *   <li>{@link org.xtext.smaC.impl.CompanyImpl#getNameAttributeCity <em>Name Attribute City</em>}</li>
 *   <li>{@link org.xtext.smaC.impl.CompanyImpl#getEmailAttributeCompany <em>Email Attribute Company</em>}</li>
 *   <li>{@link org.xtext.smaC.impl.CompanyImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.smaC.impl.CompanyImpl#getMapping <em>Mapping</em>}</li>
 *   <li>{@link org.xtext.smaC.impl.CompanyImpl#getStructs <em>Structs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CompanyImpl extends MinimalEObjectImpl.Container implements Company
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getNameAttributeAddress() <em>Name Attribute Address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameAttributeAddress()
   * @generated
   * @ordered
   */
  protected static final String NAME_ATTRIBUTE_ADDRESS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNameAttributeAddress() <em>Name Attribute Address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameAttributeAddress()
   * @generated
   * @ordered
   */
  protected String nameAttributeAddress = NAME_ATTRIBUTE_ADDRESS_EDEFAULT;

  /**
   * The default value of the '{@link #getNameAttributeCompany() <em>Name Attribute Company</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameAttributeCompany()
   * @generated
   * @ordered
   */
  protected static final String NAME_ATTRIBUTE_COMPANY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNameAttributeCompany() <em>Name Attribute Company</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameAttributeCompany()
   * @generated
   * @ordered
   */
  protected String nameAttributeCompany = NAME_ATTRIBUTE_COMPANY_EDEFAULT;

  /**
   * The default value of the '{@link #getNameAttributeCity() <em>Name Attribute City</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameAttributeCity()
   * @generated
   * @ordered
   */
  protected static final String NAME_ATTRIBUTE_CITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNameAttributeCity() <em>Name Attribute City</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameAttributeCity()
   * @generated
   * @ordered
   */
  protected String nameAttributeCity = NAME_ATTRIBUTE_CITY_EDEFAULT;

  /**
   * The default value of the '{@link #getEmailAttributeCompany() <em>Email Attribute Company</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmailAttributeCompany()
   * @generated
   * @ordered
   */
  protected static final String EMAIL_ATTRIBUTE_COMPANY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEmailAttributeCompany() <em>Email Attribute Company</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmailAttributeCompany()
   * @generated
   * @ordered
   */
  protected String emailAttributeCompany = EMAIL_ATTRIBUTE_COMPANY_EDEFAULT;

  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected EList<Properties> properties;

  /**
   * The cached value of the '{@link #getMapping() <em>Mapping</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMapping()
   * @generated
   * @ordered
   */
  protected EList<Mapping> mapping;

  /**
   * The cached value of the '{@link #getStructs() <em>Structs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStructs()
   * @generated
   * @ordered
   */
  protected EList<PersonalizedStruct> structs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CompanyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmaCPackage.Literals.COMPANY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmaCPackage.COMPANY__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNameAttributeAddress()
  {
    return nameAttributeAddress;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNameAttributeAddress(String newNameAttributeAddress)
  {
    String oldNameAttributeAddress = nameAttributeAddress;
    nameAttributeAddress = newNameAttributeAddress;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmaCPackage.COMPANY__NAME_ATTRIBUTE_ADDRESS, oldNameAttributeAddress, nameAttributeAddress));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNameAttributeCompany()
  {
    return nameAttributeCompany;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNameAttributeCompany(String newNameAttributeCompany)
  {
    String oldNameAttributeCompany = nameAttributeCompany;
    nameAttributeCompany = newNameAttributeCompany;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmaCPackage.COMPANY__NAME_ATTRIBUTE_COMPANY, oldNameAttributeCompany, nameAttributeCompany));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNameAttributeCity()
  {
    return nameAttributeCity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNameAttributeCity(String newNameAttributeCity)
  {
    String oldNameAttributeCity = nameAttributeCity;
    nameAttributeCity = newNameAttributeCity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmaCPackage.COMPANY__NAME_ATTRIBUTE_CITY, oldNameAttributeCity, nameAttributeCity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEmailAttributeCompany()
  {
    return emailAttributeCompany;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEmailAttributeCompany(String newEmailAttributeCompany)
  {
    String oldEmailAttributeCompany = emailAttributeCompany;
    emailAttributeCompany = newEmailAttributeCompany;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmaCPackage.COMPANY__EMAIL_ATTRIBUTE_COMPANY, oldEmailAttributeCompany, emailAttributeCompany));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Properties> getProperties()
  {
    if (properties == null)
    {
      properties = new EObjectContainmentEList<Properties>(Properties.class, this, SmaCPackage.COMPANY__PROPERTIES);
    }
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Mapping> getMapping()
  {
    if (mapping == null)
    {
      mapping = new EObjectContainmentEList<Mapping>(Mapping.class, this, SmaCPackage.COMPANY__MAPPING);
    }
    return mapping;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PersonalizedStruct> getStructs()
  {
    if (structs == null)
    {
      structs = new EObjectContainmentEList<PersonalizedStruct>(PersonalizedStruct.class, this, SmaCPackage.COMPANY__STRUCTS);
    }
    return structs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SmaCPackage.COMPANY__PROPERTIES:
        return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
      case SmaCPackage.COMPANY__MAPPING:
        return ((InternalEList<?>)getMapping()).basicRemove(otherEnd, msgs);
      case SmaCPackage.COMPANY__STRUCTS:
        return ((InternalEList<?>)getStructs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmaCPackage.COMPANY__NAME:
        return getName();
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_ADDRESS:
        return getNameAttributeAddress();
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_COMPANY:
        return getNameAttributeCompany();
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_CITY:
        return getNameAttributeCity();
      case SmaCPackage.COMPANY__EMAIL_ATTRIBUTE_COMPANY:
        return getEmailAttributeCompany();
      case SmaCPackage.COMPANY__PROPERTIES:
        return getProperties();
      case SmaCPackage.COMPANY__MAPPING:
        return getMapping();
      case SmaCPackage.COMPANY__STRUCTS:
        return getStructs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmaCPackage.COMPANY__NAME:
        setName((String)newValue);
        return;
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_ADDRESS:
        setNameAttributeAddress((String)newValue);
        return;
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_COMPANY:
        setNameAttributeCompany((String)newValue);
        return;
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_CITY:
        setNameAttributeCity((String)newValue);
        return;
      case SmaCPackage.COMPANY__EMAIL_ATTRIBUTE_COMPANY:
        setEmailAttributeCompany((String)newValue);
        return;
      case SmaCPackage.COMPANY__PROPERTIES:
        getProperties().clear();
        getProperties().addAll((Collection<? extends Properties>)newValue);
        return;
      case SmaCPackage.COMPANY__MAPPING:
        getMapping().clear();
        getMapping().addAll((Collection<? extends Mapping>)newValue);
        return;
      case SmaCPackage.COMPANY__STRUCTS:
        getStructs().clear();
        getStructs().addAll((Collection<? extends PersonalizedStruct>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmaCPackage.COMPANY__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_ADDRESS:
        setNameAttributeAddress(NAME_ATTRIBUTE_ADDRESS_EDEFAULT);
        return;
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_COMPANY:
        setNameAttributeCompany(NAME_ATTRIBUTE_COMPANY_EDEFAULT);
        return;
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_CITY:
        setNameAttributeCity(NAME_ATTRIBUTE_CITY_EDEFAULT);
        return;
      case SmaCPackage.COMPANY__EMAIL_ATTRIBUTE_COMPANY:
        setEmailAttributeCompany(EMAIL_ATTRIBUTE_COMPANY_EDEFAULT);
        return;
      case SmaCPackage.COMPANY__PROPERTIES:
        getProperties().clear();
        return;
      case SmaCPackage.COMPANY__MAPPING:
        getMapping().clear();
        return;
      case SmaCPackage.COMPANY__STRUCTS:
        getStructs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmaCPackage.COMPANY__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_ADDRESS:
        return NAME_ATTRIBUTE_ADDRESS_EDEFAULT == null ? nameAttributeAddress != null : !NAME_ATTRIBUTE_ADDRESS_EDEFAULT.equals(nameAttributeAddress);
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_COMPANY:
        return NAME_ATTRIBUTE_COMPANY_EDEFAULT == null ? nameAttributeCompany != null : !NAME_ATTRIBUTE_COMPANY_EDEFAULT.equals(nameAttributeCompany);
      case SmaCPackage.COMPANY__NAME_ATTRIBUTE_CITY:
        return NAME_ATTRIBUTE_CITY_EDEFAULT == null ? nameAttributeCity != null : !NAME_ATTRIBUTE_CITY_EDEFAULT.equals(nameAttributeCity);
      case SmaCPackage.COMPANY__EMAIL_ATTRIBUTE_COMPANY:
        return EMAIL_ATTRIBUTE_COMPANY_EDEFAULT == null ? emailAttributeCompany != null : !EMAIL_ATTRIBUTE_COMPANY_EDEFAULT.equals(emailAttributeCompany);
      case SmaCPackage.COMPANY__PROPERTIES:
        return properties != null && !properties.isEmpty();
      case SmaCPackage.COMPANY__MAPPING:
        return mapping != null && !mapping.isEmpty();
      case SmaCPackage.COMPANY__STRUCTS:
        return structs != null && !structs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", nameAttributeAddress: ");
    result.append(nameAttributeAddress);
    result.append(", nameAttributeCompany: ");
    result.append(nameAttributeCompany);
    result.append(", nameAttributeCity: ");
    result.append(nameAttributeCity);
    result.append(", emailAttributeCompany: ");
    result.append(emailAttributeCompany);
    result.append(')');
    return result.toString();
  }

} //CompanyImpl
