/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.smaC.InputParam;
import org.xtext.smaC.OverrideModifier;
import org.xtext.smaC.SmaCPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Override Modifier</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.impl.OverrideModifierImpl#getInputparamsOverride <em>Inputparams Override</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OverrideModifierImpl extends MinimalEObjectImpl.Container implements OverrideModifier
{
  /**
   * The cached value of the '{@link #getInputparamsOverride() <em>Inputparams Override</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputparamsOverride()
   * @generated
   * @ordered
   */
  protected EList<InputParam> inputparamsOverride;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OverrideModifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmaCPackage.Literals.OVERRIDE_MODIFIER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InputParam> getInputparamsOverride()
  {
    if (inputparamsOverride == null)
    {
      inputparamsOverride = new EObjectContainmentEList<InputParam>(InputParam.class, this, SmaCPackage.OVERRIDE_MODIFIER__INPUTPARAMS_OVERRIDE);
    }
    return inputparamsOverride;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SmaCPackage.OVERRIDE_MODIFIER__INPUTPARAMS_OVERRIDE:
        return ((InternalEList<?>)getInputparamsOverride()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmaCPackage.OVERRIDE_MODIFIER__INPUTPARAMS_OVERRIDE:
        return getInputparamsOverride();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmaCPackage.OVERRIDE_MODIFIER__INPUTPARAMS_OVERRIDE:
        getInputparamsOverride().clear();
        getInputparamsOverride().addAll((Collection<? extends InputParam>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmaCPackage.OVERRIDE_MODIFIER__INPUTPARAMS_OVERRIDE:
        getInputparamsOverride().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmaCPackage.OVERRIDE_MODIFIER__INPUTPARAMS_OVERRIDE:
        return inputparamsOverride != null && !inputparamsOverride.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //OverrideModifierImpl
