/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.smaC.Mapping;
import org.xtext.smaC.PersonalizedStruct;
import org.xtext.smaC.Properties;
import org.xtext.smaC.SmaCPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Personalized Struct</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.impl.PersonalizedStructImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.smaC.impl.PersonalizedStructImpl#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.smaC.impl.PersonalizedStructImpl#getMapping <em>Mapping</em>}</li>
 *   <li>{@link org.xtext.smaC.impl.PersonalizedStructImpl#getStructs <em>Structs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PersonalizedStructImpl extends MinimalEObjectImpl.Container implements PersonalizedStruct
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getProperties() <em>Properties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProperties()
   * @generated
   * @ordered
   */
  protected EList<Properties> properties;

  /**
   * The cached value of the '{@link #getMapping() <em>Mapping</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMapping()
   * @generated
   * @ordered
   */
  protected EList<Mapping> mapping;

  /**
   * The cached value of the '{@link #getStructs() <em>Structs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStructs()
   * @generated
   * @ordered
   */
  protected EList<PersonalizedStruct> structs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PersonalizedStructImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmaCPackage.Literals.PERSONALIZED_STRUCT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmaCPackage.PERSONALIZED_STRUCT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Properties> getProperties()
  {
    if (properties == null)
    {
      properties = new EObjectContainmentEList<Properties>(Properties.class, this, SmaCPackage.PERSONALIZED_STRUCT__PROPERTIES);
    }
    return properties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Mapping> getMapping()
  {
    if (mapping == null)
    {
      mapping = new EObjectContainmentEList<Mapping>(Mapping.class, this, SmaCPackage.PERSONALIZED_STRUCT__MAPPING);
    }
    return mapping;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PersonalizedStruct> getStructs()
  {
    if (structs == null)
    {
      structs = new EObjectContainmentEList<PersonalizedStruct>(PersonalizedStruct.class, this, SmaCPackage.PERSONALIZED_STRUCT__STRUCTS);
    }
    return structs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SmaCPackage.PERSONALIZED_STRUCT__PROPERTIES:
        return ((InternalEList<?>)getProperties()).basicRemove(otherEnd, msgs);
      case SmaCPackage.PERSONALIZED_STRUCT__MAPPING:
        return ((InternalEList<?>)getMapping()).basicRemove(otherEnd, msgs);
      case SmaCPackage.PERSONALIZED_STRUCT__STRUCTS:
        return ((InternalEList<?>)getStructs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmaCPackage.PERSONALIZED_STRUCT__NAME:
        return getName();
      case SmaCPackage.PERSONALIZED_STRUCT__PROPERTIES:
        return getProperties();
      case SmaCPackage.PERSONALIZED_STRUCT__MAPPING:
        return getMapping();
      case SmaCPackage.PERSONALIZED_STRUCT__STRUCTS:
        return getStructs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmaCPackage.PERSONALIZED_STRUCT__NAME:
        setName((String)newValue);
        return;
      case SmaCPackage.PERSONALIZED_STRUCT__PROPERTIES:
        getProperties().clear();
        getProperties().addAll((Collection<? extends Properties>)newValue);
        return;
      case SmaCPackage.PERSONALIZED_STRUCT__MAPPING:
        getMapping().clear();
        getMapping().addAll((Collection<? extends Mapping>)newValue);
        return;
      case SmaCPackage.PERSONALIZED_STRUCT__STRUCTS:
        getStructs().clear();
        getStructs().addAll((Collection<? extends PersonalizedStruct>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmaCPackage.PERSONALIZED_STRUCT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case SmaCPackage.PERSONALIZED_STRUCT__PROPERTIES:
        getProperties().clear();
        return;
      case SmaCPackage.PERSONALIZED_STRUCT__MAPPING:
        getMapping().clear();
        return;
      case SmaCPackage.PERSONALIZED_STRUCT__STRUCTS:
        getStructs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmaCPackage.PERSONALIZED_STRUCT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case SmaCPackage.PERSONALIZED_STRUCT__PROPERTIES:
        return properties != null && !properties.isEmpty();
      case SmaCPackage.PERSONALIZED_STRUCT__MAPPING:
        return mapping != null && !mapping.isEmpty();
      case SmaCPackage.PERSONALIZED_STRUCT__STRUCTS:
        return structs != null && !structs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //PersonalizedStructImpl
