/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.smaC.PropertyUInteger;
import org.xtext.smaC.SmaCPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Property UInteger</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PropertyUIntegerImpl extends PropertiesImpl implements PropertyUInteger
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PropertyUIntegerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmaCPackage.Literals.PROPERTY_UINTEGER;
  }

} //PropertyUIntegerImpl
