/*
 * generated by Xtext 2.34.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalSmaCParser;
import org.xtext.services.SmaCGrammarAccess;

public class SmaCParser extends AbstractAntlrParser {

	@Inject
	private SmaCGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmaCParser createParser(XtextTokenStream stream) {
		return new InternalSmaCParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "File";
	}

	public SmaCGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmaCGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
