/**
 *
 * $Id$
 */
package pcn.validation;

import org.eclipse.emf.common.util.EList;

import pcn.PCNDependency;
import pcn.PCNProcessEntity;

/**
 * A sample validator interface for {@link pcn.PCNDiagram}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PCNDiagramValidator {
	boolean validate();

	boolean validateDiagramEntities(EList<PCNProcessEntity> value);

	boolean validateDiagramDependencies(EList<PCNDependency> value);

	boolean validateEntities(EList<PCNProcessEntity> value);
	boolean validateDependencies(EList<PCNDependency> value);
}
