/**
 *
 * $Id$
 */
package pcn.validation;

import org.eclipse.emf.common.util.EList;

import pcn.PCNProcessEntity;
import pcn.PCNProcessStep;

/**
 * A sample validator interface for {@link pcn.PCNProcessEntity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PCNProcessEntityValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateOrder(int value);
	boolean validateBackEntity(PCNProcessEntity value);
	boolean validateNextEntity(PCNProcessEntity value);
	boolean validateLeftDirectInteractions(EList<PCNProcessStep> value);
	boolean validateLeftSurrogateInteractions(EList<PCNProcessStep> value);
	boolean validateCenterIndependentInteractionsActivities(EList<PCNProcessStep> value);

	boolean validateIndependentInteractionsActivities(EList<PCNProcessStep> value);
	boolean validateRightSurrogateInteractions(EList<PCNProcessStep> value);
	boolean validateRightDirectInteractions(EList<PCNProcessStep> value);
}
