/**
 *
 * $Id$
 */
package pcn.validation;

import pcn.PCNProcessStep;

/**
 * A sample validator interface for {@link pcn.PCNProcessStepDependency}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PCNProcessStepDependencyValidator {
	boolean validate();

	boolean validateSourceProcessStep(PCNProcessStep value);
	boolean validateTargetProcessStep(PCNProcessStep value);
}
