/**
 *
 * $Id$
 */
package pcn.validation;

import org.eclipse.emf.common.util.EList;

import pcn.PCNMonetaryBenefit;
import pcn.PCNMonetaryCost;
import pcn.PCNNonMonetaryBenefit;
import pcn.PCNNonMonetaryCost;

/**
 * A sample validator interface for {@link pcn.PCNProcessStepWithTags}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PCNProcessStepWithTagsValidator {
	boolean validate();

	boolean validateNonMonetaryBenefits(EList<PCNNonMonetaryBenefit> value);
	boolean validateNonMonetaryCosts(EList<PCNNonMonetaryCost> value);
	boolean validateMonetaryBenefits(EList<PCNMonetaryBenefit> value);
	boolean validateMonetaryCosts(EList<PCNMonetaryCost> value);
}
