/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.provider;


import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ViewerNotification;

import org.xtext.smaC.AbstractContract;
import org.xtext.smaC.SmaCFactory;
import org.xtext.smaC.SmaCPackage;

/**
 * This is the item provider adapter for a {@link org.xtext.smaC.AbstractContract} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AbstractContractItemProvider extends ElementItemProvider {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AbstractContractItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

			addSuperTypePropertyDescriptor(object);
		}
		return itemPropertyDescriptors;
	}

	/**
	 * This adds a property descriptor for the Super Type feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addSuperTypePropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_AbstractContract_superType_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_AbstractContract_superType_feature", "_UI_AbstractContract_type"),
				 SmaCPackage.Literals.ABSTRACT_CONTRACT__SUPER_TYPE,
				 true,
				 false,
				 true,
				 null,
				 null,
				 null));
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(SmaCPackage.Literals.ABSTRACT_CONTRACT__MODIFIERS);
			childrenFeatures.add(SmaCPackage.Literals.ABSTRACT_CONTRACT__EVENTS);
			childrenFeatures.add(SmaCPackage.Literals.ABSTRACT_CONTRACT__ERRORS);
			childrenFeatures.add(SmaCPackage.Literals.ABSTRACT_CONTRACT__CLAUSES);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns AbstractContract.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/AbstractContract"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		String label = ((AbstractContract)object).getName();
		return label == null || label.length() == 0 ?
			getString("_UI_AbstractContract_type") :
			getString("_UI_AbstractContract_type") + " " + label;
	}


	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(AbstractContract.class)) {
			case SmaCPackage.ABSTRACT_CONTRACT__MODIFIERS:
			case SmaCPackage.ABSTRACT_CONTRACT__EVENTS:
			case SmaCPackage.ABSTRACT_CONTRACT__ERRORS:
			case SmaCPackage.ABSTRACT_CONTRACT__CLAUSES:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.ABSTRACT_CONTRACT__MODIFIERS,
				 SmaCFactory.eINSTANCE.createModifier()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.ABSTRACT_CONTRACT__EVENTS,
				 SmaCFactory.eINSTANCE.createEvent()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.ABSTRACT_CONTRACT__ERRORS,
				 SmaCFactory.eINSTANCE.createError()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.ABSTRACT_CONTRACT__CLAUSES,
				 SmaCFactory.eINSTANCE.createDeclarationFunctionAbstractContract()));
	}

}
