/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.provider;


import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.emf.edit.provider.ItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ItemProviderAdapter;
import org.eclipse.emf.edit.provider.ViewerNotification;

import org.xtext.smaC.Condition;
import org.xtext.smaC.SmaCFactory;
import org.xtext.smaC.SmaCPackage;

/**
 * This is the item provider adapter for a {@link org.xtext.smaC.Condition} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ConditionItemProvider 
	extends ItemProviderAdapter
	implements
		IEditingDomainItemProvider,
		IStructuredItemContentProvider,
		ITreeItemContentProvider,
		IItemLabelProvider,
		IItemPropertySource {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ConditionItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

			addConditionPropertyDescriptor(object);
			addExpressionsPropertyDescriptor(object);
			addEventPropertyDescriptor(object);
			addExpressionsElsePropertyDescriptor(object);
			addEventElsePropertyDescriptor(object);
		}
		return itemPropertyDescriptors;
	}

	/**
	 * This adds a property descriptor for the Condition feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addConditionPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_Condition_condition_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_Condition_condition_feature", "_UI_Condition_type"),
				 SmaCPackage.Literals.CONDITION__CONDITION,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Expressions feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addExpressionsPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_Condition_expressions_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_Condition_expressions_feature", "_UI_Condition_type"),
				 SmaCPackage.Literals.CONDITION__EXPRESSIONS,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Event feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addEventPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_Condition_event_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_Condition_event_feature", "_UI_Condition_type"),
				 SmaCPackage.Literals.CONDITION__EVENT,
				 true,
				 false,
				 true,
				 null,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Expressions Else feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addExpressionsElsePropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_Condition_expressionsElse_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_Condition_expressionsElse_feature", "_UI_Condition_type"),
				 SmaCPackage.Literals.CONDITION__EXPRESSIONS_ELSE,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Event Else feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addEventElsePropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_Condition_eventElse_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_Condition_eventElse_feature", "_UI_Condition_type"),
				 SmaCPackage.Literals.CONDITION__EVENT_ELSE,
				 true,
				 false,
				 true,
				 null,
				 null,
				 null));
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__RESTRICTION);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__PROPERTIES);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__CONDITIONAL_EXPR);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__UNDETERMINEDLOOPS);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__DETERMINEDLOOPS);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__INPUT_PARAMS_EVENT);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__RESTRICTION_ELSE);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__CONDITIONAL_EXPR_ELSE);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__UNDETERMINEDLOOPS_ELSE);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__DETERMINEDLOOPS_ELSE);
			childrenFeatures.add(SmaCPackage.Literals.CONDITION__INPUT_PARAMS_EVENT_ELSE);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns Condition.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/Condition"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		String label = ((Condition)object).getCondition();
		return label == null || label.length() == 0 ?
			getString("_UI_Condition_type") :
			getString("_UI_Condition_type") + " " + label;
	}


	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(Condition.class)) {
			case SmaCPackage.CONDITION__CONDITION:
			case SmaCPackage.CONDITION__EXPRESSIONS:
			case SmaCPackage.CONDITION__EXPRESSIONS_ELSE:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), false, true));
				return;
			case SmaCPackage.CONDITION__RESTRICTION:
			case SmaCPackage.CONDITION__PROPERTIES:
			case SmaCPackage.CONDITION__CONDITIONAL_EXPR:
			case SmaCPackage.CONDITION__UNDETERMINEDLOOPS:
			case SmaCPackage.CONDITION__DETERMINEDLOOPS:
			case SmaCPackage.CONDITION__INPUT_PARAMS_EVENT:
			case SmaCPackage.CONDITION__RESTRICTION_ELSE:
			case SmaCPackage.CONDITION__PROPERTIES_ELSE:
			case SmaCPackage.CONDITION__CONDITIONAL_EXPR_ELSE:
			case SmaCPackage.CONDITION__UNDETERMINEDLOOPS_ELSE:
			case SmaCPackage.CONDITION__DETERMINEDLOOPS_ELSE:
			case SmaCPackage.CONDITION__INPUT_PARAMS_EVENT_ELSE:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__RESTRICTION,
				 SmaCFactory.eINSTANCE.createRestrictionClause()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__RESTRICTION,
				 SmaCFactory.eINSTANCE.createRestriction()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__RESTRICTION,
				 SmaCFactory.eINSTANCE.createRestrictionGas()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__RESTRICTION,
				 SmaCFactory.eINSTANCE.createAssert()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createProperties()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyString()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyInteger()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyFloat()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyUInteger()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyBoolean()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyAddress()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyIdentifier()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyUser()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyCompany()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyBytes()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__CONDITIONAL_EXPR,
				 SmaCFactory.eINSTANCE.createCondition()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__UNDETERMINEDLOOPS,
				 SmaCFactory.eINSTANCE.createUnDeterminedLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__UNDETERMINEDLOOPS,
				 SmaCFactory.eINSTANCE.createWhileLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__UNDETERMINEDLOOPS,
				 SmaCFactory.eINSTANCE.createDoWhileLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__DETERMINEDLOOPS,
				 SmaCFactory.eINSTANCE.createForLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__INPUT_PARAMS_EVENT,
				 SmaCFactory.eINSTANCE.createInputParam()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__INPUT_PARAMS_EVENT,
				 SmaCFactory.eINSTANCE.createMappingDeclaration()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__RESTRICTION_ELSE,
				 SmaCFactory.eINSTANCE.createRestrictionClause()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__RESTRICTION_ELSE,
				 SmaCFactory.eINSTANCE.createRestriction()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__RESTRICTION_ELSE,
				 SmaCFactory.eINSTANCE.createRestrictionGas()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__RESTRICTION_ELSE,
				 SmaCFactory.eINSTANCE.createAssert()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createProperties()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createPropertyString()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createPropertyInteger()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createPropertyFloat()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createPropertyUInteger()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createPropertyBoolean()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createPropertyAddress()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createPropertyIdentifier()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createPropertyUser()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createPropertyCompany()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE,
				 SmaCFactory.eINSTANCE.createPropertyBytes()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__CONDITIONAL_EXPR_ELSE,
				 SmaCFactory.eINSTANCE.createCondition()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__UNDETERMINEDLOOPS_ELSE,
				 SmaCFactory.eINSTANCE.createUnDeterminedLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__UNDETERMINEDLOOPS_ELSE,
				 SmaCFactory.eINSTANCE.createWhileLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__UNDETERMINEDLOOPS_ELSE,
				 SmaCFactory.eINSTANCE.createDoWhileLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__DETERMINEDLOOPS_ELSE,
				 SmaCFactory.eINSTANCE.createForLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__INPUT_PARAMS_EVENT_ELSE,
				 SmaCFactory.eINSTANCE.createInputParam()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.CONDITION__INPUT_PARAMS_EVENT_ELSE,
				 SmaCFactory.eINSTANCE.createMappingDeclaration()));
	}

	/**
	 * This returns the label text for {@link org.eclipse.emf.edit.command.CreateChildCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getCreateChildText(Object owner, Object feature, Object child, Collection<?> selection) {
		Object childFeature = feature;
		Object childObject = child;

		boolean qualify =
			childFeature == SmaCPackage.Literals.CONDITION__RESTRICTION ||
			childFeature == SmaCPackage.Literals.CONDITION__RESTRICTION_ELSE ||
			childFeature == SmaCPackage.Literals.CONDITION__PROPERTIES ||
			childFeature == SmaCPackage.Literals.CONDITION__PROPERTIES_ELSE ||
			childFeature == SmaCPackage.Literals.CONDITION__CONDITIONAL_EXPR ||
			childFeature == SmaCPackage.Literals.CONDITION__CONDITIONAL_EXPR_ELSE ||
			childFeature == SmaCPackage.Literals.CONDITION__UNDETERMINEDLOOPS ||
			childFeature == SmaCPackage.Literals.CONDITION__UNDETERMINEDLOOPS_ELSE ||
			childFeature == SmaCPackage.Literals.CONDITION__DETERMINEDLOOPS ||
			childFeature == SmaCPackage.Literals.CONDITION__DETERMINEDLOOPS_ELSE ||
			childFeature == SmaCPackage.Literals.CONDITION__INPUT_PARAMS_EVENT ||
			childFeature == SmaCPackage.Literals.CONDITION__INPUT_PARAMS_EVENT_ELSE;

		if (qualify) {
			return getString
				("_UI_CreateChild_text2",
				 new Object[] { getTypeText(childObject), getFeatureText(childFeature), getTypeText(owner) });
		}
		return super.getCreateChildText(owner, feature, child, selection);
	}

	/**
	 * Return the resource locator for this item provider's resources.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ResourceLocator getResourceLocator() {
		return SmaCEditPlugin.INSTANCE;
	}

}
