/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.provider;


import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.emf.edit.provider.ItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ItemProviderAdapter;
import org.eclipse.emf.edit.provider.ViewerNotification;

import org.xtext.smaC.SmaCFactory;
import org.xtext.smaC.SmaCPackage;
import org.xtext.smaC.UnDeterminedLoop;

/**
 * This is the item provider adapter for a {@link org.xtext.smaC.UnDeterminedLoop} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class UnDeterminedLoopItemProvider 
	extends ItemProviderAdapter
	implements
		IEditingDomainItemProvider,
		IStructuredItemContentProvider,
		ITreeItemContentProvider,
		IItemLabelProvider,
		IItemPropertySource {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public UnDeterminedLoopItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

			addConditionPropertyDescriptor(object);
			addEventPropertyDescriptor(object);
			addExpressionsPropertyDescriptor(object);
		}
		return itemPropertyDescriptors;
	}

	/**
	 * This adds a property descriptor for the Condition feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addConditionPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_UnDeterminedLoop_condition_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_UnDeterminedLoop_condition_feature", "_UI_UnDeterminedLoop_type"),
				 SmaCPackage.Literals.UN_DETERMINED_LOOP__CONDITION,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Event feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addEventPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_UnDeterminedLoop_event_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_UnDeterminedLoop_event_feature", "_UI_UnDeterminedLoop_type"),
				 SmaCPackage.Literals.UN_DETERMINED_LOOP__EVENT,
				 true,
				 false,
				 true,
				 null,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Expressions feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addExpressionsPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_UnDeterminedLoop_expressions_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_UnDeterminedLoop_expressions_feature", "_UI_UnDeterminedLoop_type"),
				 SmaCPackage.Literals.UN_DETERMINED_LOOP__EXPRESSIONS,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(SmaCPackage.Literals.UN_DETERMINED_LOOP__GASRESTRICTION);
			childrenFeatures.add(SmaCPackage.Literals.UN_DETERMINED_LOOP__RESTRICTION);
			childrenFeatures.add(SmaCPackage.Literals.UN_DETERMINED_LOOP__CONDITIONS);
			childrenFeatures.add(SmaCPackage.Literals.UN_DETERMINED_LOOP__UNDETERMINEDLOOPS);
			childrenFeatures.add(SmaCPackage.Literals.UN_DETERMINED_LOOP__DETERMINEDLOOPS);
			childrenFeatures.add(SmaCPackage.Literals.UN_DETERMINED_LOOP__INPUT_PARAMS);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns UnDeterminedLoop.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/UnDeterminedLoop"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		String label = ((UnDeterminedLoop)object).getCondition();
		return label == null || label.length() == 0 ?
			getString("_UI_UnDeterminedLoop_type") :
			getString("_UI_UnDeterminedLoop_type") + " " + label;
	}


	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(UnDeterminedLoop.class)) {
			case SmaCPackage.UN_DETERMINED_LOOP__CONDITION:
			case SmaCPackage.UN_DETERMINED_LOOP__EXPRESSIONS:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), false, true));
				return;
			case SmaCPackage.UN_DETERMINED_LOOP__GASRESTRICTION:
			case SmaCPackage.UN_DETERMINED_LOOP__RESTRICTION:
			case SmaCPackage.UN_DETERMINED_LOOP__CONDITIONS:
			case SmaCPackage.UN_DETERMINED_LOOP__UNDETERMINEDLOOPS:
			case SmaCPackage.UN_DETERMINED_LOOP__DETERMINEDLOOPS:
			case SmaCPackage.UN_DETERMINED_LOOP__INPUT_PARAMS:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__GASRESTRICTION,
				 SmaCFactory.eINSTANCE.createRestrictionGas()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__RESTRICTION,
				 SmaCFactory.eINSTANCE.createRestrictionClause()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__RESTRICTION,
				 SmaCFactory.eINSTANCE.createRestriction()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__RESTRICTION,
				 SmaCFactory.eINSTANCE.createRestrictionGas()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__RESTRICTION,
				 SmaCFactory.eINSTANCE.createAssert()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__CONDITIONS,
				 SmaCFactory.eINSTANCE.createCondition()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__UNDETERMINEDLOOPS,
				 SmaCFactory.eINSTANCE.createUnDeterminedLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__UNDETERMINEDLOOPS,
				 SmaCFactory.eINSTANCE.createWhileLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__UNDETERMINEDLOOPS,
				 SmaCFactory.eINSTANCE.createDoWhileLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__DETERMINEDLOOPS,
				 SmaCFactory.eINSTANCE.createForLoop()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__INPUT_PARAMS,
				 SmaCFactory.eINSTANCE.createInputParam()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.UN_DETERMINED_LOOP__INPUT_PARAMS,
				 SmaCFactory.eINSTANCE.createMappingDeclaration()));
	}

	/**
	 * This returns the label text for {@link org.eclipse.emf.edit.command.CreateChildCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getCreateChildText(Object owner, Object feature, Object child, Collection<?> selection) {
		Object childFeature = feature;
		Object childObject = child;

		boolean qualify =
			childFeature == SmaCPackage.Literals.UN_DETERMINED_LOOP__GASRESTRICTION ||
			childFeature == SmaCPackage.Literals.UN_DETERMINED_LOOP__RESTRICTION;

		if (qualify) {
			return getString
				("_UI_CreateChild_text2",
				 new Object[] { getTypeText(childObject), getFeatureText(childFeature), getTypeText(owner) });
		}
		return super.getCreateChildText(owner, feature, child, selection);
	}

	/**
	 * Return the resource locator for this item provider's resources.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ResourceLocator getResourceLocator() {
		return SmaCEditPlugin.INSTANCE;
	}

}
