/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.provider;


import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.emf.edit.provider.ItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ItemProviderAdapter;
import org.eclipse.emf.edit.provider.ViewerNotification;

import org.xtext.smaC.SmaCFactory;
import org.xtext.smaC.SmaCPackage;
import org.xtext.smaC.User;

/**
 * This is the item provider adapter for a {@link org.xtext.smaC.User} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class UserItemProvider 
	extends ItemProviderAdapter
	implements
		IEditingDomainItemProvider,
		IStructuredItemContentProvider,
		ITreeItemContentProvider,
		IItemLabelProvider,
		IItemPropertySource {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public UserItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

			addNamePropertyDescriptor(object);
			addNameAttributeAddressPropertyDescriptor(object);
			addNameAttributeUserPropertyDescriptor(object);
			addNameAttributeSurnameUserPropertyDescriptor(object);
			addEmailAttributeUserPropertyDescriptor(object);
		}
		return itemPropertyDescriptors;
	}

	/**
	 * This adds a property descriptor for the Name feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addNamePropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_User_name_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_User_name_feature", "_UI_User_type"),
				 SmaCPackage.Literals.USER__NAME,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Name Attribute Address feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addNameAttributeAddressPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_User_nameAttributeAddress_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_User_nameAttributeAddress_feature", "_UI_User_type"),
				 SmaCPackage.Literals.USER__NAME_ATTRIBUTE_ADDRESS,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Name Attribute User feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addNameAttributeUserPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_User_nameAttributeUser_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_User_nameAttributeUser_feature", "_UI_User_type"),
				 SmaCPackage.Literals.USER__NAME_ATTRIBUTE_USER,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Name Attribute Surname User feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addNameAttributeSurnameUserPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_User_nameAttributeSurnameUser_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_User_nameAttributeSurnameUser_feature", "_UI_User_type"),
				 SmaCPackage.Literals.USER__NAME_ATTRIBUTE_SURNAME_USER,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Email Attribute User feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addEmailAttributeUserPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_User_emailAttributeUser_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_User_emailAttributeUser_feature", "_UI_User_type"),
				 SmaCPackage.Literals.USER__EMAIL_ATTRIBUTE_USER,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(SmaCPackage.Literals.USER__PROPERTIES);
			childrenFeatures.add(SmaCPackage.Literals.USER__MAPPING);
			childrenFeatures.add(SmaCPackage.Literals.USER__STRUCTS);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns User.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/User"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		String label = ((User)object).getName();
		return label == null || label.length() == 0 ?
			getString("_UI_User_type") :
			getString("_UI_User_type") + " " + label;
	}


	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(User.class)) {
			case SmaCPackage.USER__NAME:
			case SmaCPackage.USER__NAME_ATTRIBUTE_ADDRESS:
			case SmaCPackage.USER__NAME_ATTRIBUTE_USER:
			case SmaCPackage.USER__NAME_ATTRIBUTE_SURNAME_USER:
			case SmaCPackage.USER__EMAIL_ATTRIBUTE_USER:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), false, true));
				return;
			case SmaCPackage.USER__PROPERTIES:
			case SmaCPackage.USER__MAPPING:
			case SmaCPackage.USER__STRUCTS:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createProperties()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyString()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyInteger()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyFloat()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyUInteger()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyBoolean()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyAddress()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyIdentifier()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyUser()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyCompany()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__PROPERTIES,
				 SmaCFactory.eINSTANCE.createPropertyBytes()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__MAPPING,
				 SmaCFactory.eINSTANCE.createMapping()));

		newChildDescriptors.add
			(createChildParameter
				(SmaCPackage.Literals.USER__STRUCTS,
				 SmaCFactory.eINSTANCE.createPersonalizedStruct()));
	}

	/**
	 * Return the resource locator for this item provider's resources.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ResourceLocator getResourceLocator() {
		return SmaCEditPlugin.INSTANCE;
	}

}
