/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.AbstractContract#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link org.xtext.smaC.AbstractContract#getModifiers <em>Modifiers</em>}</li>
 *   <li>{@link org.xtext.smaC.AbstractContract#getEvents <em>Events</em>}</li>
 *   <li>{@link org.xtext.smaC.AbstractContract#getErrors <em>Errors</em>}</li>
 *   <li>{@link org.xtext.smaC.AbstractContract#getClauses <em>Clauses</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getAbstractContract()
 * @model
 * @generated
 */
public interface AbstractContract extends Element
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference list.
   * The list contents are of type {@link org.xtext.smaC.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference list.
   * @see org.xtext.smaC.SmaCPackage#getAbstractContract_SuperType()
   * @model
   * @generated
   */
  EList<Element> getSuperType();

  /**
   * Returns the value of the '<em><b>Modifiers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Modifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modifiers</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getAbstractContract_Modifiers()
   * @model containment="true"
   * @generated
   */
  EList<Modifier> getModifiers();

  /**
   * Returns the value of the '<em><b>Events</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getAbstractContract_Events()
   * @model containment="true"
   * @generated
   */
  EList<Event> getEvents();

  /**
   * Returns the value of the '<em><b>Errors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Error}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Errors</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getAbstractContract_Errors()
   * @model containment="true"
   * @generated
   */
  EList<org.xtext.smaC.Error> getErrors();

  /**
   * Returns the value of the '<em><b>Clauses</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.DeclarationFunctionAbstractContract}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clauses</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getAbstractContract_Clauses()
   * @model containment="true"
   * @generated
   */
  EList<DeclarationFunctionAbstractContract> getClauses();

} // AbstractContract
