/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Comparation Operator</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.smaC.SmaCPackage#getComparationOperator()
 * @model
 * @generated
 */
public enum ComparationOperator implements Enumerator
{
  /**
   * The '<em><b>Greather Than</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GREATHER_THAN_VALUE
   * @generated
   * @ordered
   */
  GREATHER_THAN(0, "GreatherThan", ">"),

  /**
   * The '<em><b>Less Than</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LESS_THAN_VALUE
   * @generated
   * @ordered
   */
  LESS_THAN(1, "LessThan", "<"),

  /**
   * The '<em><b>Greather Or Equal Than</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GREATHER_OR_EQUAL_THAN_VALUE
   * @generated
   * @ordered
   */
  GREATHER_OR_EQUAL_THAN(2, "GreatherOrEqualThan", ">="),

  /**
   * The '<em><b>Less Or Equal Than</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LESS_OR_EQUAL_THAN_VALUE
   * @generated
   * @ordered
   */
  LESS_OR_EQUAL_THAN(3, "LessOrEqualThan", "<="),

  /**
   * The '<em><b>Equal To</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EQUAL_TO_VALUE
   * @generated
   * @ordered
   */
  EQUAL_TO(4, "EqualTo", "=="),

  /**
   * The '<em><b>Not Equal To</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NOT_EQUAL_TO_VALUE
   * @generated
   * @ordered
   */
  NOT_EQUAL_TO(5, "NotEqualTo", "!=");

  /**
   * The '<em><b>Greather Than</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GREATHER_THAN
   * @model name="GreatherThan" literal="&gt;"
   * @generated
   * @ordered
   */
  public static final int GREATHER_THAN_VALUE = 0;

  /**
   * The '<em><b>Less Than</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LESS_THAN
   * @model name="LessThan" literal="&lt;"
   * @generated
   * @ordered
   */
  public static final int LESS_THAN_VALUE = 1;

  /**
   * The '<em><b>Greather Or Equal Than</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GREATHER_OR_EQUAL_THAN
   * @model name="GreatherOrEqualThan" literal="&gt;="
   * @generated
   * @ordered
   */
  public static final int GREATHER_OR_EQUAL_THAN_VALUE = 2;

  /**
   * The '<em><b>Less Or Equal Than</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LESS_OR_EQUAL_THAN
   * @model name="LessOrEqualThan" literal="&lt;="
   * @generated
   * @ordered
   */
  public static final int LESS_OR_EQUAL_THAN_VALUE = 3;

  /**
   * The '<em><b>Equal To</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EQUAL_TO
   * @model name="EqualTo" literal="=="
   * @generated
   * @ordered
   */
  public static final int EQUAL_TO_VALUE = 4;

  /**
   * The '<em><b>Not Equal To</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NOT_EQUAL_TO
   * @model name="NotEqualTo" literal="!="
   * @generated
   * @ordered
   */
  public static final int NOT_EQUAL_TO_VALUE = 5;

  /**
   * An array of all the '<em><b>Comparation Operator</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ComparationOperator[] VALUES_ARRAY =
    new ComparationOperator[]
    {
      GREATHER_THAN,
      LESS_THAN,
      GREATHER_OR_EQUAL_THAN,
      LESS_OR_EQUAL_THAN,
      EQUAL_TO,
      NOT_EQUAL_TO,
    };

  /**
   * A public read-only list of all the '<em><b>Comparation Operator</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ComparationOperator> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Comparation Operator</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ComparationOperator get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ComparationOperator result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Comparation Operator</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ComparationOperator getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ComparationOperator result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Comparation Operator</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ComparationOperator get(int value)
  {
    switch (value)
    {
      case GREATHER_THAN_VALUE: return GREATHER_THAN;
      case LESS_THAN_VALUE: return LESS_THAN;
      case GREATHER_OR_EQUAL_THAN_VALUE: return GREATHER_OR_EQUAL_THAN;
      case LESS_OR_EQUAL_THAN_VALUE: return LESS_OR_EQUAL_THAN;
      case EQUAL_TO_VALUE: return EQUAL_TO;
      case NOT_EQUAL_TO_VALUE: return NOT_EQUAL_TO;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ComparationOperator(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ComparationOperator
