/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constructor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.Constructor#getInputParams <em>Input Params</em>}</li>
 *   <li>{@link org.xtext.smaC.Constructor#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.smaC.Constructor#getConstructorContractInherance <em>Constructor Contract Inherance</em>}</li>
 *   <li>{@link org.xtext.smaC.Constructor#getInputParamsConstructorContractInherance <em>Input Params Constructor Contract Inherance</em>}</li>
 *   <li>{@link org.xtext.smaC.Constructor#getPayable <em>Payable</em>}</li>
 *   <li>{@link org.xtext.smaC.Constructor#getRestrictions <em>Restrictions</em>}</li>
 *   <li>{@link org.xtext.smaC.Constructor#getConditions <em>Conditions</em>}</li>
 *   <li>{@link org.xtext.smaC.Constructor#getUndeterminedLoops <em>Undetermined Loops</em>}</li>
 *   <li>{@link org.xtext.smaC.Constructor#getDeterminedLoops <em>Determined Loops</em>}</li>
 *   <li>{@link org.xtext.smaC.Constructor#getAttributesInitialization <em>Attributes Initialization</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getConstructor()
 * @model
 * @generated
 */
public interface Constructor extends EObject
{
  /**
   * Returns the value of the '<em><b>Input Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.InputParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Params</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getConstructor_InputParams()
   * @model containment="true"
   * @generated
   */
  EList<InputParam> getInputParams();

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.smaC.SmaCPackage#getConstructor_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Constructor#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Constructor Contract Inherance</b></em>' reference list.
   * The list contents are of type {@link org.xtext.smaC.Contract}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constructor Contract Inherance</em>' reference list.
   * @see org.xtext.smaC.SmaCPackage#getConstructor_ConstructorContractInherance()
   * @model
   * @generated
   */
  EList<Contract> getConstructorContractInherance();

  /**
   * Returns the value of the '<em><b>Input Params Constructor Contract Inherance</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.InputParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Params Constructor Contract Inherance</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getConstructor_InputParamsConstructorContractInherance()
   * @model containment="true"
   * @generated
   */
  EList<InputParam> getInputParamsConstructorContractInherance();

  /**
   * Returns the value of the '<em><b>Payable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Payable</em>' attribute.
   * @see #setPayable(String)
   * @see org.xtext.smaC.SmaCPackage#getConstructor_Payable()
   * @model
   * @generated
   */
  String getPayable();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Constructor#getPayable <em>Payable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Payable</em>' attribute.
   * @see #getPayable()
   * @generated
   */
  void setPayable(String value);

  /**
   * Returns the value of the '<em><b>Restrictions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.RestrictionClause}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Restrictions</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getConstructor_Restrictions()
   * @model containment="true"
   * @generated
   */
  EList<RestrictionClause> getRestrictions();

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getConstructor_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditions();

  /**
   * Returns the value of the '<em><b>Undetermined Loops</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.UnDeterminedLoop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Undetermined Loops</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getConstructor_UndeterminedLoops()
   * @model containment="true"
   * @generated
   */
  EList<UnDeterminedLoop> getUndeterminedLoops();

  /**
   * Returns the value of the '<em><b>Determined Loops</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.ForLoop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Determined Loops</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getConstructor_DeterminedLoops()
   * @model containment="true"
   * @generated
   */
  EList<ForLoop> getDeterminedLoops();

  /**
   * Returns the value of the '<em><b>Attributes Initialization</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes Initialization</em>' attribute list.
   * @see org.xtext.smaC.SmaCPackage#getConstructor_AttributesInitialization()
   * @model unique="false"
   * @generated
   */
  EList<String> getAttributesInitialization();

} // Constructor
