/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration Function Interface</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.DeclarationFunctionInterface#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.smaC.DeclarationFunctionInterface#getInputParams <em>Input Params</em>}</li>
 *   <li>{@link org.xtext.smaC.DeclarationFunctionInterface#getModifier <em>Modifier</em>}</li>
 *   <li>{@link org.xtext.smaC.DeclarationFunctionInterface#getOutputParams <em>Output Params</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getDeclarationFunctionInterface()
 * @model
 * @generated
 */
public interface DeclarationFunctionInterface extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.smaC.SmaCPackage#getDeclarationFunctionInterface_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.smaC.DeclarationFunctionInterface#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Input Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.InputParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Params</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getDeclarationFunctionInterface_InputParams()
   * @model containment="true"
   * @generated
   */
  EList<InputParam> getInputParams();

  /**
   * Returns the value of the '<em><b>Modifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modifier</em>' attribute.
   * @see #setModifier(String)
   * @see org.xtext.smaC.SmaCPackage#getDeclarationFunctionInterface_Modifier()
   * @model
   * @generated
   */
  String getModifier();

  /**
   * Sets the value of the '{@link org.xtext.smaC.DeclarationFunctionInterface#getModifier <em>Modifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modifier</em>' attribute.
   * @see #getModifier()
   * @generated
   */
  void setModifier(String value);

  /**
   * Returns the value of the '<em><b>Output Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.OutputParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Params</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getDeclarationFunctionInterface_OutputParams()
   * @model containment="true"
   * @generated
   */
  EList<OutputParam> getOutputParams();

} // DeclarationFunctionInterface
