/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Do While Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.smaC.SmaCPackage#getDoWhileLoop()
 * @model
 * @generated
 */
public interface DoWhileLoop extends UnDeterminedLoop
{
} // DoWhileLoop
