/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interface</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.Interface#getInterfaceEvents <em>Interface Events</em>}</li>
 *   <li>{@link org.xtext.smaC.Interface#getInterfaceFunction <em>Interface Function</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getInterface()
 * @model
 * @generated
 */
public interface Interface extends Element
{
  /**
   * Returns the value of the '<em><b>Interface Events</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interface Events</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getInterface_InterfaceEvents()
   * @model containment="true"
   * @generated
   */
  EList<Event> getInterfaceEvents();

  /**
   * Returns the value of the '<em><b>Interface Function</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.DeclarationFunctionInterface}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interface Function</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getInterface_InterfaceFunction()
   * @model containment="true"
   * @generated
   */
  EList<DeclarationFunctionInterface> getInterfaceFunction();

} // Interface
