/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Library</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.Library#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.smaC.Library#getStructs <em>Structs</em>}</li>
 *   <li>{@link org.xtext.smaC.Library#getEnums <em>Enums</em>}</li>
 *   <li>{@link org.xtext.smaC.Library#getFunctions <em>Functions</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getLibrary()
 * @model
 * @generated
 */
public interface Library extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.smaC.SmaCPackage#getLibrary_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Library#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Structs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.PersonalizedStruct}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Structs</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getLibrary_Structs()
   * @model containment="true"
   * @generated
   */
  EList<PersonalizedStruct> getStructs();

  /**
   * Returns the value of the '<em><b>Enums</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Enum}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enums</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getLibrary_Enums()
   * @model containment="true"
   * @generated
   */
  EList<org.xtext.smaC.Enum> getEnums();

  /**
   * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Clause}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getLibrary_Functions()
   * @model containment="true"
   * @generated
   */
  EList<Clause> getFunctions();

} // Library
