/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.Mapping#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.smaC.Mapping#getArray <em>Array</em>}</li>
 *   <li>{@link org.xtext.smaC.Mapping#getConstant <em>Constant</em>}</li>
 *   <li>{@link org.xtext.smaC.Mapping#getVisibility <em>Visibility</em>}</li>
 *   <li>{@link org.xtext.smaC.Mapping#getStorageData <em>Storage Data</em>}</li>
 *   <li>{@link org.xtext.smaC.Mapping#getNameMapping <em>Name Mapping</em>}</li>
 *   <li>{@link org.xtext.smaC.Mapping#getInicialization <em>Inicialization</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getMapping()
 * @model
 * @generated
 */
public interface Mapping extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(MappingDeclaration)
   * @see org.xtext.smaC.SmaCPackage#getMapping_Type()
   * @model containment="true"
   * @generated
   */
  MappingDeclaration getType();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Mapping#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(MappingDeclaration value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' attribute.
   * @see #setArray(String)
   * @see org.xtext.smaC.SmaCPackage#getMapping_Array()
   * @model
   * @generated
   */
  String getArray();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Mapping#getArray <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' attribute.
   * @see #getArray()
   * @generated
   */
  void setArray(String value);

  /**
   * Returns the value of the '<em><b>Constant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' attribute.
   * @see #setConstant(String)
   * @see org.xtext.smaC.SmaCPackage#getMapping_Constant()
   * @model
   * @generated
   */
  String getConstant();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Mapping#getConstant <em>Constant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' attribute.
   * @see #getConstant()
   * @generated
   */
  void setConstant(String value);

  /**
   * Returns the value of the '<em><b>Visibility</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.smaC.Visibility}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibility</em>' attribute.
   * @see org.xtext.smaC.Visibility
   * @see #setVisibility(Visibility)
   * @see org.xtext.smaC.SmaCPackage#getMapping_Visibility()
   * @model
   * @generated
   */
  Visibility getVisibility();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Mapping#getVisibility <em>Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibility</em>' attribute.
   * @see org.xtext.smaC.Visibility
   * @see #getVisibility()
   * @generated
   */
  void setVisibility(Visibility value);

  /**
   * Returns the value of the '<em><b>Storage Data</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.smaC.StorageData}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Storage Data</em>' attribute.
   * @see org.xtext.smaC.StorageData
   * @see #setStorageData(StorageData)
   * @see org.xtext.smaC.SmaCPackage#getMapping_StorageData()
   * @model
   * @generated
   */
  StorageData getStorageData();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Mapping#getStorageData <em>Storage Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Storage Data</em>' attribute.
   * @see org.xtext.smaC.StorageData
   * @see #getStorageData()
   * @generated
   */
  void setStorageData(StorageData value);

  /**
   * Returns the value of the '<em><b>Name Mapping</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Mapping</em>' attribute.
   * @see #setNameMapping(String)
   * @see org.xtext.smaC.SmaCPackage#getMapping_NameMapping()
   * @model
   * @generated
   */
  String getNameMapping();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Mapping#getNameMapping <em>Name Mapping</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Mapping</em>' attribute.
   * @see #getNameMapping()
   * @generated
   */
  void setNameMapping(String value);

  /**
   * Returns the value of the '<em><b>Inicialization</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inicialization</em>' attribute.
   * @see #setInicialization(String)
   * @see org.xtext.smaC.SmaCPackage#getMapping_Inicialization()
   * @model
   * @generated
   */
  String getInicialization();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Mapping#getInicialization <em>Inicialization</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inicialization</em>' attribute.
   * @see #getInicialization()
   * @generated
   */
  void setInicialization(String value);

} // Mapping
