/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.Modifier#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.smaC.Modifier#getInputParams <em>Input Params</em>}</li>
 *   <li>{@link org.xtext.smaC.Modifier#getConditionRestricion <em>Condition Restricion</em>}</li>
 *   <li>{@link org.xtext.smaC.Modifier#getExpressionsAssignValueBeforeMark <em>Expressions Assign Value Before Mark</em>}</li>
 *   <li>{@link org.xtext.smaC.Modifier#getConditionsBeforeMark <em>Conditions Before Mark</em>}</li>
 *   <li>{@link org.xtext.smaC.Modifier#getExpressionsAssignValueAfterMark <em>Expressions Assign Value After Mark</em>}</li>
 *   <li>{@link org.xtext.smaC.Modifier#getConditionsAfterMark <em>Conditions After Mark</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getModifier()
 * @model
 * @generated
 */
public interface Modifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.smaC.SmaCPackage#getModifier_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Modifier#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Input Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.InputParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Params</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getModifier_InputParams()
   * @model containment="true"
   * @generated
   */
  EList<InputParam> getInputParams();

  /**
   * Returns the value of the '<em><b>Condition Restricion</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.RestrictionClause}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Restricion</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getModifier_ConditionRestricion()
   * @model containment="true"
   * @generated
   */
  EList<RestrictionClause> getConditionRestricion();

  /**
   * Returns the value of the '<em><b>Expressions Assign Value Before Mark</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions Assign Value Before Mark</em>' attribute list.
   * @see org.xtext.smaC.SmaCPackage#getModifier_ExpressionsAssignValueBeforeMark()
   * @model unique="false"
   * @generated
   */
  EList<String> getExpressionsAssignValueBeforeMark();

  /**
   * Returns the value of the '<em><b>Conditions Before Mark</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Before Mark</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getModifier_ConditionsBeforeMark()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditionsBeforeMark();

  /**
   * Returns the value of the '<em><b>Expressions Assign Value After Mark</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions Assign Value After Mark</em>' attribute list.
   * @see org.xtext.smaC.SmaCPackage#getModifier_ExpressionsAssignValueAfterMark()
   * @model unique="false"
   * @generated
   */
  EList<String> getExpressionsAssignValueAfterMark();

  /**
   * Returns the value of the '<em><b>Conditions After Mark</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions After Mark</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getModifier_ConditionsAfterMark()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditionsAfterMark();

} // Modifier
