/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Personalized Struct</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.PersonalizedStruct#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.smaC.PersonalizedStruct#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.smaC.PersonalizedStruct#getMapping <em>Mapping</em>}</li>
 *   <li>{@link org.xtext.smaC.PersonalizedStruct#getStructs <em>Structs</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getPersonalizedStruct()
 * @model
 * @generated
 */
public interface PersonalizedStruct extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.smaC.SmaCPackage#getPersonalizedStruct_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.smaC.PersonalizedStruct#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Properties}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getPersonalizedStruct_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Properties> getProperties();

  /**
   * Returns the value of the '<em><b>Mapping</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Mapping}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapping</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getPersonalizedStruct_Mapping()
   * @model containment="true"
   * @generated
   */
  EList<Mapping> getMapping();

  /**
   * Returns the value of the '<em><b>Structs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.PersonalizedStruct}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Structs</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getPersonalizedStruct_Structs()
   * @model containment="true"
   * @generated
   */
  EList<PersonalizedStruct> getStructs();

} // PersonalizedStruct
