/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property User</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.smaC.SmaCPackage#getPropertyUser()
 * @model
 * @generated
 */
public interface PropertyUser extends Properties
{
} // PropertyUser
