/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.Properties#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.smaC.Properties#getArray <em>Array</em>}</li>
 *   <li>{@link org.xtext.smaC.Properties#getConstant <em>Constant</em>}</li>
 *   <li>{@link org.xtext.smaC.Properties#getVisibility <em>Visibility</em>}</li>
 *   <li>{@link org.xtext.smaC.Properties#getStorageData <em>Storage Data</em>}</li>
 *   <li>{@link org.xtext.smaC.Properties#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.smaC.Properties#getInicialization <em>Inicialization</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getProperties()
 * @model
 * @generated
 */
public interface Properties extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.smaC.SmaCPackage#getProperties_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Properties#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' attribute.
   * @see #setArray(String)
   * @see org.xtext.smaC.SmaCPackage#getProperties_Array()
   * @model
   * @generated
   */
  String getArray();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Properties#getArray <em>Array</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' attribute.
   * @see #getArray()
   * @generated
   */
  void setArray(String value);

  /**
   * Returns the value of the '<em><b>Constant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' attribute.
   * @see #setConstant(String)
   * @see org.xtext.smaC.SmaCPackage#getProperties_Constant()
   * @model
   * @generated
   */
  String getConstant();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Properties#getConstant <em>Constant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' attribute.
   * @see #getConstant()
   * @generated
   */
  void setConstant(String value);

  /**
   * Returns the value of the '<em><b>Visibility</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.smaC.Visibility}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibility</em>' attribute.
   * @see org.xtext.smaC.Visibility
   * @see #setVisibility(Visibility)
   * @see org.xtext.smaC.SmaCPackage#getProperties_Visibility()
   * @model
   * @generated
   */
  Visibility getVisibility();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Properties#getVisibility <em>Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibility</em>' attribute.
   * @see org.xtext.smaC.Visibility
   * @see #getVisibility()
   * @generated
   */
  void setVisibility(Visibility value);

  /**
   * Returns the value of the '<em><b>Storage Data</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.smaC.StorageData}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Storage Data</em>' attribute.
   * @see org.xtext.smaC.StorageData
   * @see #setStorageData(StorageData)
   * @see org.xtext.smaC.SmaCPackage#getProperties_StorageData()
   * @model
   * @generated
   */
  StorageData getStorageData();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Properties#getStorageData <em>Storage Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Storage Data</em>' attribute.
   * @see org.xtext.smaC.StorageData
   * @see #getStorageData()
   * @generated
   */
  void setStorageData(StorageData value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.smaC.SmaCPackage#getProperties_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Properties#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Inicialization</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inicialization</em>' attribute.
   * @see #setInicialization(String)
   * @see org.xtext.smaC.SmaCPackage#getProperties_Inicialization()
   * @model
   * @generated
   */
  String getInicialization();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Properties#getInicialization <em>Inicialization</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inicialization</em>' attribute.
   * @see #getInicialization()
   * @generated
   */
  void setInicialization(String value);

} // Properties
