/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Identifier</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.smaC.SmaCPackage#getPropertyIdentifier()
 * @model
 * @generated
 */
public interface PropertyIdentifier extends Properties
{
} // PropertyIdentifier
