/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Restriction Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.RestrictionClause#getExpr1 <em>Expr1</em>}</li>
 *   <li>{@link org.xtext.smaC.RestrictionClause#getOperator <em>Operator</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getRestrictionClause()
 * @model
 * @generated
 */
public interface RestrictionClause extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr1</em>' attribute.
   * @see #setExpr1(String)
   * @see org.xtext.smaC.SmaCPackage#getRestrictionClause_Expr1()
   * @model
   * @generated
   */
  String getExpr1();

  /**
   * Sets the value of the '{@link org.xtext.smaC.RestrictionClause#getExpr1 <em>Expr1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr1</em>' attribute.
   * @see #getExpr1()
   * @generated
   */
  void setExpr1(String value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.smaC.ComparationOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see org.xtext.smaC.ComparationOperator
   * @see #setOperator(ComparationOperator)
   * @see org.xtext.smaC.SmaCPackage#getRestrictionClause_Operator()
   * @model
   * @generated
   */
  ComparationOperator getOperator();

  /**
   * Sets the value of the '{@link org.xtext.smaC.RestrictionClause#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see org.xtext.smaC.ComparationOperator
   * @see #getOperator()
   * @generated
   */
  void setOperator(ComparationOperator value);

} // RestrictionClause
