/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Restriction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.Restriction#getExpr2 <em>Expr2</em>}</li>
 *   <li>{@link org.xtext.smaC.Restriction#getMessage <em>Message</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getRestriction()
 * @model
 * @generated
 */
public interface Restriction extends RestrictionClause
{
  /**
   * Returns the value of the '<em><b>Expr2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr2</em>' attribute.
   * @see #setExpr2(String)
   * @see org.xtext.smaC.SmaCPackage#getRestriction_Expr2()
   * @model
   * @generated
   */
  String getExpr2();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Restriction#getExpr2 <em>Expr2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr2</em>' attribute.
   * @see #getExpr2()
   * @generated
   */
  void setExpr2(String value);

  /**
   * Returns the value of the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' attribute.
   * @see #setMessage(String)
   * @see org.xtext.smaC.SmaCPackage#getRestriction_Message()
   * @model
   * @generated
   */
  String getMessage();

  /**
   * Sets the value of the '{@link org.xtext.smaC.Restriction#getMessage <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' attribute.
   * @see #getMessage()
   * @generated
   */
  void setMessage(String value);

} // Restriction
