/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Un Determined Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.UnDeterminedLoop#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.smaC.UnDeterminedLoop#getGasrestriction <em>Gasrestriction</em>}</li>
 *   <li>{@link org.xtext.smaC.UnDeterminedLoop#getRestriction <em>Restriction</em>}</li>
 *   <li>{@link org.xtext.smaC.UnDeterminedLoop#getConditions <em>Conditions</em>}</li>
 *   <li>{@link org.xtext.smaC.UnDeterminedLoop#getUndeterminedloops <em>Undeterminedloops</em>}</li>
 *   <li>{@link org.xtext.smaC.UnDeterminedLoop#getDeterminedloops <em>Determinedloops</em>}</li>
 *   <li>{@link org.xtext.smaC.UnDeterminedLoop#getEvent <em>Event</em>}</li>
 *   <li>{@link org.xtext.smaC.UnDeterminedLoop#getInputParams <em>Input Params</em>}</li>
 *   <li>{@link org.xtext.smaC.UnDeterminedLoop#getExpressions <em>Expressions</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getUnDeterminedLoop()
 * @model
 * @generated
 */
public interface UnDeterminedLoop extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see org.xtext.smaC.SmaCPackage#getUnDeterminedLoop_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link org.xtext.smaC.UnDeterminedLoop#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

  /**
   * Returns the value of the '<em><b>Gasrestriction</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.RestrictionGas}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gasrestriction</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getUnDeterminedLoop_Gasrestriction()
   * @model containment="true"
   * @generated
   */
  EList<RestrictionGas> getGasrestriction();

  /**
   * Returns the value of the '<em><b>Restriction</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.RestrictionClause}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Restriction</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getUnDeterminedLoop_Restriction()
   * @model containment="true"
   * @generated
   */
  EList<RestrictionClause> getRestriction();

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getUnDeterminedLoop_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditions();

  /**
   * Returns the value of the '<em><b>Undeterminedloops</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.UnDeterminedLoop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Undeterminedloops</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getUnDeterminedLoop_Undeterminedloops()
   * @model containment="true"
   * @generated
   */
  EList<UnDeterminedLoop> getUndeterminedloops();

  /**
   * Returns the value of the '<em><b>Determinedloops</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.ForLoop}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Determinedloops</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getUnDeterminedLoop_Determinedloops()
   * @model containment="true"
   * @generated
   */
  EList<ForLoop> getDeterminedloops();

  /**
   * Returns the value of the '<em><b>Event</b></em>' reference list.
   * The list contents are of type {@link org.xtext.smaC.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' reference list.
   * @see org.xtext.smaC.SmaCPackage#getUnDeterminedLoop_Event()
   * @model
   * @generated
   */
  EList<Event> getEvent();

  /**
   * Returns the value of the '<em><b>Input Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.InputParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Params</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getUnDeterminedLoop_InputParams()
   * @model containment="true"
   * @generated
   */
  EList<InputParam> getInputParams();

  /**
   * Returns the value of the '<em><b>Expressions</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' attribute list.
   * @see org.xtext.smaC.SmaCPackage#getUnDeterminedLoop_Expressions()
   * @model unique="false"
   * @generated
   */
  EList<String> getExpressions();

} // UnDeterminedLoop
