/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaC.User#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.smaC.User#getNameAttributeAddress <em>Name Attribute Address</em>}</li>
 *   <li>{@link org.xtext.smaC.User#getNameAttributeUser <em>Name Attribute User</em>}</li>
 *   <li>{@link org.xtext.smaC.User#getNameAttributeSurnameUser <em>Name Attribute Surname User</em>}</li>
 *   <li>{@link org.xtext.smaC.User#getEmailAttributeUser <em>Email Attribute User</em>}</li>
 *   <li>{@link org.xtext.smaC.User#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.smaC.User#getMapping <em>Mapping</em>}</li>
 *   <li>{@link org.xtext.smaC.User#getStructs <em>Structs</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaC.SmaCPackage#getUser()
 * @model
 * @generated
 */
public interface User extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.smaC.SmaCPackage#getUser_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.smaC.User#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Name Attribute Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Attribute Address</em>' attribute.
   * @see #setNameAttributeAddress(String)
   * @see org.xtext.smaC.SmaCPackage#getUser_NameAttributeAddress()
   * @model
   * @generated
   */
  String getNameAttributeAddress();

  /**
   * Sets the value of the '{@link org.xtext.smaC.User#getNameAttributeAddress <em>Name Attribute Address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Attribute Address</em>' attribute.
   * @see #getNameAttributeAddress()
   * @generated
   */
  void setNameAttributeAddress(String value);

  /**
   * Returns the value of the '<em><b>Name Attribute User</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Attribute User</em>' attribute.
   * @see #setNameAttributeUser(String)
   * @see org.xtext.smaC.SmaCPackage#getUser_NameAttributeUser()
   * @model
   * @generated
   */
  String getNameAttributeUser();

  /**
   * Sets the value of the '{@link org.xtext.smaC.User#getNameAttributeUser <em>Name Attribute User</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Attribute User</em>' attribute.
   * @see #getNameAttributeUser()
   * @generated
   */
  void setNameAttributeUser(String value);

  /**
   * Returns the value of the '<em><b>Name Attribute Surname User</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Attribute Surname User</em>' attribute.
   * @see #setNameAttributeSurnameUser(String)
   * @see org.xtext.smaC.SmaCPackage#getUser_NameAttributeSurnameUser()
   * @model
   * @generated
   */
  String getNameAttributeSurnameUser();

  /**
   * Sets the value of the '{@link org.xtext.smaC.User#getNameAttributeSurnameUser <em>Name Attribute Surname User</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Attribute Surname User</em>' attribute.
   * @see #getNameAttributeSurnameUser()
   * @generated
   */
  void setNameAttributeSurnameUser(String value);

  /**
   * Returns the value of the '<em><b>Email Attribute User</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email Attribute User</em>' attribute.
   * @see #setEmailAttributeUser(String)
   * @see org.xtext.smaC.SmaCPackage#getUser_EmailAttributeUser()
   * @model
   * @generated
   */
  String getEmailAttributeUser();

  /**
   * Sets the value of the '{@link org.xtext.smaC.User#getEmailAttributeUser <em>Email Attribute User</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email Attribute User</em>' attribute.
   * @see #getEmailAttributeUser()
   * @generated
   */
  void setEmailAttributeUser(String value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Properties}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getUser_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Properties> getProperties();

  /**
   * Returns the value of the '<em><b>Mapping</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.Mapping}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapping</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getUser_Mapping()
   * @model containment="true"
   * @generated
   */
  EList<Mapping> getMapping();

  /**
   * Returns the value of the '<em><b>Structs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smaC.PersonalizedStruct}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Structs</em>' containment reference list.
   * @see org.xtext.smaC.SmaCPackage#getUser_Structs()
   * @model containment="true"
   * @generated
   */
  EList<PersonalizedStruct> getStructs();

} // User
