/*
 * generated by Xtext 2.34.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.SmaCRuntimeModule;
import org.xtext.SmaCStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SmaCIdeSetup extends SmaCStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SmaCRuntimeModule(), new SmaCIdeModule()));
	}
	
}
