/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.smaC.OverrideModifier;
import org.xtext.smaC.SmaCFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Override Modifier</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class OverrideModifierTest extends TestCase {

	/**
	 * The fixture for this Override Modifier test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OverrideModifier fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(OverrideModifierTest.class);
	}

	/**
	 * Constructs a new Override Modifier test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public OverrideModifierTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Override Modifier test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(OverrideModifier fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Override Modifier test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OverrideModifier getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCFactory.eINSTANCE.createOverrideModifier());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //OverrideModifierTest
