/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.tests;

import junit.textui.TestRunner;

import org.xtext.smaC.PropertyBoolean;
import org.xtext.smaC.SmaCFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Property Boolean</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class PropertyBooleanTest extends PropertiesTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(PropertyBooleanTest.class);
	}

	/**
	 * Constructs a new Property Boolean test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PropertyBooleanTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Property Boolean test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected PropertyBoolean getFixture() {
		return (PropertyBoolean)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCFactory.eINSTANCE.createPropertyBoolean());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //PropertyBooleanTest
