/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.tests;

import junit.textui.TestRunner;

import org.xtext.smaC.PropertyString;
import org.xtext.smaC.SmaCFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Property String</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class PropertyStringTest extends PropertiesTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(PropertyStringTest.class);
	}

	/**
	 * Constructs a new Property String test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PropertyStringTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Property String test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected PropertyString getFixture() {
		return (PropertyString)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCFactory.eINSTANCE.createPropertyString());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //PropertyStringTest
