/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.smaC.RestrictionClause;
import org.xtext.smaC.SmaCFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Restriction Clause</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class RestrictionClauseTest extends TestCase {

	/**
	 * The fixture for this Restriction Clause test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RestrictionClause fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(RestrictionClauseTest.class);
	}

	/**
	 * Constructs a new Restriction Clause test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RestrictionClauseTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Restriction Clause test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(RestrictionClause fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Restriction Clause test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RestrictionClause getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCFactory.eINSTANCE.createRestrictionClause());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //RestrictionClauseTest
