/**
 * generated by Xtext 2.34.0
 */
package org.xtext.smaC.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test suite for the '<em><b>SmaC</b></em>' model.
 * <!-- end-user-doc -->
 * @generated
 */
public class SmaCAllTests extends TestSuite {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(suite());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static Test suite() {
		TestSuite suite = new SmaCAllTests("SmaC Tests");
		suite.addTest(SmaCTests.suite());
		return suite;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SmaCAllTests(String name) {
		super(name);
	}

} //SmaCAllTests
